FROM debian:jessie

MAINTAINER Joel De Jesus "joel.dejesus@samurai-fintech.com"

ENV DEBIAN_FRONTEND noninteractive

ARG proxy

RUN if [ -z ${proxy+x} ]; then echo "Going WITHOUT an apt proxy" 1>&2; else echo "Acquire::http::Proxy \"http://$proxy\";" > /etc/apt/apt.conf.d/proxy.conf && echo "Going WITH an apt proxy" 1>&2 ; fi 

RUN apt-get update && apt-get install -y nginx

EXPOSE 80

CMD ["/usr/sbin/nginx","-g","daemon off;"]
